name: cytochat
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - nvidia/label/cuda-11.8.0
  - nvidia
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - cuda=11.8.0=0
  - cuda-cccl=11.8.89=0
  - cuda-command-line-tools=11.8.0=0
  - cuda-compiler=11.8.0=0
  - cuda-cudart=11.8.89=0
  - cuda-cudart-dev=11.8.89=0
  - cuda-cuobjdump=11.8.86=0
  - cuda-cupti=11.8.87=0
  - cuda-cuxxfilt=11.8.86=0
  - cuda-demo-suite=11.8.86=0
  - cuda-documentation=11.8.86=0
  - cuda-driver-dev=11.8.89=0
  - cuda-gdb=11.8.86=0
  - cuda-libraries=11.8.0=0
  - cuda-libraries-dev=11.8.0=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=11.8.86=0
  - cuda-nsight-compute=11.8.0=0
  - cuda-nvcc=11.8.89=0
  - cuda-nvdisasm=11.8.86=0
  - cuda-nvml-dev=11.8.86=0
  - cuda-nvprof=11.8.87=0
  - cuda-nvprune=11.8.86=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvrtc-dev=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-nvvp=11.8.87=0
  - cuda-profiler-api=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cuda-sanitizer-api=11.8.86=0
  - cuda-toolkit=11.8.0=0
  - cuda-tools=11.8.0=0
  - cuda-visual-tools=11.8.0=0
  - gds-tools=1.4.0.31=0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcufile=1.4.0.31=0
  - libcufile-dev=1.4.0.31=0
  - libcurand=10.3.0.86=0
  - libcurand-dev=10.3.0.86=0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.0.3=0
  - ncurses=6.4=h6a678d5_0
  - nsight-compute=2022.3.0.22=0
  - openssl=1.1.1w=h7f8727e_0
  - pip=25.0=py310h06a4308_0
  - python=3.10.0=h12debd9_5
  - readline=8.2=h5eee18b_0
  - setuptools=75.8.0=py310h06a4308_0
  - sqlite=3.38.2=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - wheel=0.45.1=py310h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.11=0
  - pip:
      - accelerate==1.5.2
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.16
      - aiohttp-cors==0.8.1
      - aiosignal==1.3.2
      - airportsdata==20250224
      - annotated-types==0.7.0
      - anyio==4.9.0
      - astor==0.8.1
      - async-timeout==5.0.1
      - attrs==25.3.0
      - audioread==3.0.1
      - av==14.3.0
      - bitsandbytes==0.43.1
      - blake3==1.0.4
      - cachetools==5.5.2
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - colorful==0.5.6
      - compressed-tensors==0.9.1
      - contourpy==1.3.1
      - cycler==0.12.1
      - datasets==3.4.1
      - decorator==5.2.1
      - deepspeed==0.16.3
      - depyf==0.18.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distlib==0.3.9
      - distro==1.9.0
      - docstring-parser==0.16
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - exceptiongroup==1.2.2
      - fastapi==0.115.12
      - ffmpy==0.5.0
      - filelock==3.18.0
      - fire==0.7.0
      - flash-attn==2.7.4.post1
      - fonttools==4.57.0
      - frozenlist==1.5.0
      - fsspec==2025.3.2
      - fuzzywuzzy==0.18.0
      - gguf==0.10.0
      - google-api-core==2.24.2
      - google-auth==2.38.0
      - googleapis-common-protos==1.69.2
      - gradio==5.21.0
      - gradio-client==1.7.2
      - groovy==0.1.2
      - grpcio==1.71.0
      - h11==0.14.0
      - hjson==3.1.0
      - httpcore==1.0.7
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.30.2
      - idna==3.10
      - imageio==2.37.0
      - importlib-metadata==8.6.1
      - interegular==0.3.3
      - jieba==0.42.1
      - jinja2==3.1.4
      - jiter==0.9.0
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.8
      - lark==1.2.2
      - lazy-loader==0.4
      - librosa==0.11.0
      - llamafactory==0.9.3.dev0
      - llvmlite==0.44.0
      - lm-format-enforcer==0.10.11
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - mistral-common==1.5.4
      - mpmath==1.3.0
      - msgpack==1.1.0
      - msgspec==0.19.0
      - multidict==6.2.0
      - multiprocess==0.70.16
      - nest-asyncio==1.6.0
      - networkx==3.3
      - ninja==1.11.1.4
      - nltk==3.9.1
      - numba==0.61.2
      - numpy==2.2.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu11==11.8.86
      - nvidia-nvtx-cu12==12.4.127
      - openai==1.72.0
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opencv-python-headless==4.11.0.86
      - openpyxl==3.1.5
      - orjson==3.10.16
      - outlines==0.1.11
      - outlines-core==0.1.26
      - packaging==24.2
      - pandas==2.2.3
      - partial-json-parser==0.2.1.1.post5
      - peft==0.15.0
      - pillow==11.0.0
      - platformdirs==4.3.7
      - pooch==1.8.2
      - prometheus-client==0.21.1
      - prometheus-fastapi-instrumentator==7.1.0
      - propcache==0.3.1
      - proto-plus==1.26.1
      - protobuf==6.30.2
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - py-spy==0.4.0
      - pyarrow==19.0.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycountry==24.6.1
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pygments==2.19.1
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==26.4.0
      - ray==2.44.1
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==14.0.0
      - rouge-chinese==1.0.3
      - rpds-py==0.24.0
      - rsa==4.9
      - ruff==0.11.4
      - safehttpx==0.1.6
      - safetensors==0.5.3
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - shtab==1.7.1
      - six==1.17.0
      - smart-open==7.1.0
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soxr==0.5.0.post1
      - sse-starlette==2.2.1
      - starlette==0.46.1
      - sympy==1.13.1
      - termcolor==3.0.1
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - tiktoken==0.9.0
      - tokenizers==0.21.1
      - tomlkit==0.13.2
      - torch==2.5.1+cu118
      - torchaudio==2.5.1+cu118
      - torchvision==0.20.1+cu118
      - tqdm==4.67.1
      - transformers==4.49.0.dev0
      - triton==3.1.0
      - trl==0.9.6
      - typer==0.15.2
      - typing-extensions==4.13.2
      - typing-inspection==0.4.0
      - tyro==0.8.14
      - tzdata==2025.2
      - urllib3==2.4.0
      - uvicorn==0.34.0
      - uvloop==0.21.0
      - virtualenv==20.30.0
      - vllm==0.7.2
      - watchfiles==1.0.5
      - websockets==15.0.1
      - wrapt==1.17.2
      - xformers==0.0.28.post3
      - xgrammar==0.1.18
      - xxhash==3.5.0
      - yarl==1.19.0
      - zipp==3.21.0
prefix: /miniconda3/envs/cytochat
